version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/devops_mongo
    depends_on:
      - mongo
    networks:
      - dev_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dev_network

  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev_network

networks:
  dev_network: